version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: project_sjk_web
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    networks:
      - sjk-network
    depends_on:
      - db
    environment:
      WAIT_HOSTS: db:3306 # Untuk menggunakan mekanisme wait-for-it atau serupa

  db:
    image: mysql:8.0
    container_name: project_sjk_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: tubes
      MYSQL_USER: sjkuser
      MYSQL_PASSWORD: sjkpassword
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - sjk-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  db_data:

networks:
  sjk-network:
