# @format

services:
  web:
    image: apache_image
    container_name: webserver
    ports:
      - "80:80"
    volumes:
      - C:\xampp\htdocs\projectsjk\webfolder:/var/www/html
    networks:
      - appsjk
networks:
  appsjk:
    external: true
